# Stripe keys
STRIPE_SECRET_KEY = "sk_test_51PqDMpJPCppLFw9f1cq51KrTnMF72w73DNgctJSntBVbvIfgwuUARCoKTWTyIyUXs2NuACWWsczRtly5KBVn5WhS00y0s8YgvM"
STRIPE_ENDPOINT_SECRET = ""

# SUPABASE KEYS
SUPABASE_URL = "https://pywjppikcsiroejzuymf.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5d2pwcGlrY3Npcm9lanp1eW1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQyNDMzODAsImV4cCI6MjAzOTgxOTM4MH0.Mf2XUAqcIQ2Uf2OkvK9MMi6lACbITke97Nj4AiFW8Z8"
REDIRECT_URL=https://airecipegen.streamlit.app


# GOOGLE AUTH
CLIENT_ID = "522831058080-1ubpjcnlikrpfoi75j3ajej5pfai3c1b.apps.googleusercontent.com"
CLIENT_SECRET = "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"

# Connect to Supabase via connection pooling with Supavisor.
DATABASE_URL = "postgresql://postgres.pywjppikcsiroejzuymf:fd3Nxpr4hU8Rbkmt@aws-0-us-west-1.pooler.supabase.com:6543/postgres"

# Direct connection to the database. Used for migrations.
DIRECT_URL = "postgres://postgres.[PROJECT_ID]:fd3Nxpr4hU8Rbkmt-0-eu-central-1.pooler.supabase.com:5432/postgres?pgbouncer=true"

testing_mode = "true"
payment_provider = "stripe"
stripe_api_key_test = "" # only needed if using Stripe
stripe_api_key = ""

# only needed if using Stripe
stripe_link_starter_test = 10
stripe_link_teams_test = 50
stripe_link_enterprise_test = 100

stripe_link_starter = 10
stripe_link_teams = 50
stripe_link_enterprise = 100

# [Optional], read more from this link: https://stripe.com/blog/billing-customer-portal
stripe_manage_billing_link = ""

stripe_product_id_starter_test = ""
stripe_product_id_teams_test = ""
stripe_product_id_enterprise_test = ""

stripe_product_id_starter = ""
stripe_product_id_teams = ""
stripe_product_id_enterprise = ""

# Postgres database password
postgres_password = "fd3Nxpr4hU8Rbkmt"